<?php

namespace App\Models;

use Database\Factories\UserFactory;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Hidden;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

#[Fillable(['name', 'email', 'password', 'pin', 'mobile', 'profile_picture', 'skills',
            'joining_date', 'employment_type', 'bank_details', 'status'])]
#[Hidden(['password', 'remember_token'])]
class User extends Authenticatable
{
    /** @use HasFactory<UserFactory> */
    use HasFactory, Notifiable, HasRoles, SoftDeletes;

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password'          => 'hashed',
            'skills'            => 'array',
            'bank_details'      => 'array',
        ];
    }

    // ── Relationships ──────────────────────────────────────────────────────

    /** Projects this user is assigned to (many-to-many via project_user). */
    public function projects()
    {
        return $this->belongsToMany(Project::class, 'project_user')
                    ->withTimestamps();
    }

    /** All earnings credited to this user. */
    public function earnings()
    {
        return $this->hasMany(Earning::class);
    }

    /** All payout requests made by this user. */
    public function payoutRequests()
    {
        return $this->hasMany(PayoutRequest::class);
    }

    /** Bank accounts registered by this user. */
    public function bankAccounts()
    {
        return $this->hasMany(BankAccount::class);
    }

    /** Primary bank account. */
    public function primaryBankAccount()
    {
        return $this->hasOne(BankAccount::class)->where('is_primary', true);
    }

    /** In-app system notifications for this user. */
    public function systemNotifications()
    {
        return $this->hasMany(SystemNotification::class);
    }

    /** Activity logs generated by this user. */
    public function activityLogs()
    {
        return $this->hasMany(ActivityLog::class);
    }

    /** Leads assigned to this user (as the responsible person). */
    public function leads()
    {
        return $this->hasMany(Lead::class, 'assigned_to');
    }

    /** Leads submitted/originated by this employee. */
    public function submittedLeads()
    {
        return $this->hasMany(Lead::class, 'user_id');
    }

    // ── Helpers ───────────────────────────────────────────────────────────

    /** Calculated available balance for payout requests. */
    public function availableBalance(): float
    {
        $totalEarned   = $this->earnings()->whereIn('status', ['cleared', 'paid'])->sum('amount');
        $totalPaid     = $this->payoutRequests()->where('status', 'paid')->sum('amount');
        $totalRequested = $this->payoutRequests()->whereIn('status', ['pending', 'approved'])->sum('amount');

        return max(0, $totalEarned - $totalPaid - $totalRequested);
    }
}
